apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  custom.cnf: |
    [mysqld]
    max_connections          = {{ .Values.mysqlConfig.max_connections }}
    max_allowed_packet       = {{ .Values.mysqlConfig.max_allowed_packet }}

    character_set_server     = {{ .Values.mysqlConfig.character_set_server }}
    collation_server         = {{ .Values.mysqlConfig.collation_server }}

    slow_query_log           = {{ .Values.mysqlConfig.slow_query_log }}
    long_query_time          = {{ .Values.mysqlConfig.long_query_time }}

    innodb_buffer_pool_size  = {{ .Values.mysqlConfig.innodb_buffer_pool_size }}

    datadir                  = /var/lib/mysql
    socket                   = /var/run/mysqld/mysqld.sock
    pid-file                 = /var/run/mysqld/mysqld.pid

    [client]
    default-character-set    = {{ .Values.mysqlConfig.character_set_server }}
    socket                   = /var/run/mysqld/mysqld.sock

{{- if .Values.initScripts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.initScriptsConfigMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
    app.kubernetes.io/component: initscripts
data:
  {{- range $filename, $content := .Values.initScripts }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}