apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault
  namespace: argocd-ns
spec:
  description: vault homelab project — custom chart
  sourceRepos:
    - https://github.com/manishdotkr/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: vault-ns
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd-ns
spec:
  project: vault
  source:
    repoURL: https://github.com/manishdotkr/homelab.git
    targetRevision: main
    path: helm/vault
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true