replicaCount: 1

image:
  repository: dumbwareio/dumbkan
  tag: latest
  pullPolicy: IfNotPresent

appName: dumbkan

env:
  siteTitle: "dumbkan"
  baseUrl: "http://board.devopsindia.dev"

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi

persistence:
  hostPath: /mnt/ssd/kubernetes/dumbkan
  mountPath: /app/data

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: board.devopsindia.dev
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"