replicaCount: 1

image:
  repository: ghcr.io/go2kart/backend
  tag: v2
  pullPolicy: IfNotPresent

appName: go2kart

resources:
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 1000Mi

persistence:
  hostPath: /mnt/ssd/kubernetes/go2kart
  mountPath: /app/data

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: go2kart-api.devopsindia.dev
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"