apiVersion: apps/v1
kind: Deployment
metadata:
  name: dumbpad-dep
  namespace: {{ .Values.namespace }}
  labels:
    app: dumbpad
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dumbpad
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: dumbpad
    spec:
      containers:
        - name: dumbpad
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SITE_TITLE
              value: {{ .Values.env.siteTitle | quote }}
            - name: BASE_URL
              value: {{ .Values.env.baseUrl | quote }}
          ports:
            - name: dumbpad
              containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
            - name: dumbpad-data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: dumbpad-data
          hostPath:
            path: {{ .Values.persistence.hostPath }}