apiVersion: v1
kind: Service
metadata:
  name: dumbpad-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: dumbpad
  type: {{ .Values.service.type }}
  sessionAffinity: None
  ports:
    - name: dumbpad
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}